version: "2"
services:

  app:
    container_name: app
    build: server/
    ports:
      - "3080:5000"
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

    stop_signal: SIGKILL


  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.2.1
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
      - grafana_db:/var/lib/grafana/data
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
  
volumes:
  grafana_data:
  grafana_db:

  # promtail:
  #   image: grafana/promtail:latest
  #   volumes:
  #     - "/var/log:/var/log"
  #     - "/var/lib/docker/containers:/var/lib/docker/containers"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - "./promtail-config.yaml:/etc/promtail/config.yaml"
  #   command: "-config.file=/etc/promtail/config.yaml"
  #   depends_on:
  #     - loki
